### ISSUE TITLE
Showing sites privacy policy when clicked

### ISSUE THREAD

**Issue by nssidhu** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#15]
How can i show my privacy policy page when clicked ?
currently i have the privacypolicy.razor page so hopping to navigate to it using Navmanager.NavigateTo('')
In case the privacy policy page is inside www root as .html, also support navigating to that html page as well as you are doing in google-maps privacy policy.

Also can i also add another link to display terms and condition ?

![image](https://user-images.githubusercontent.com/3267605/193417366-cd2175e3-facb-4fa2-9c70-d2c9af586b13.png)

**Comment by RyanTT** [comment]
Hi, currently navigating to a custom page within the same tab is not possible with those links. They always open a new tab. However, the link they open in a new tab can be customized in step 4 of the configuration guide:

```cs
builder.Services.AddCookieConsent(o =>
{
    o.PolicyUrl = ...;
});
```

**Comment by nssidhu** [comment]
for now that works, but in case of WebAssembly I have to provide the full URL and it loads the full site again.

**Comment by RyanTT** [comment]
> I have to provide the full URL and it loads the full site again.

Full site reload is inevitable at the moment sadly, but relative URLs work too here :)
