### ISSUE TITLE
How to read the consent level ?

### ISSUE THREAD

**Issue by nssidhu** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#16]
How do i know if user has denied the consent in my Razor Page ?
Is there a way to track via code in .razor page as to what has been accepted and what has been denied ?

**Comment by RyanTT** [comment]
Hi, the CookieConsentService has an EventHandler that notifies you when the preferences have changed

https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/blob/master/BytexDigital.Blazor.Components.CookieConsent/CookieConsentService.cs#L43
