### ISSUE TITLE
customize order of OpenPreferences and AcceptAll buttons

### ISSUE THREAD

**Issue by sion-corn** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#19]
Would you be able to introduce a way to customize the order of the OpenPreferences and AcceptAll buttons? I would like to display the "AcceptAll" button to be above the "OpenPreferences" button.

I am using version 1.0.17-preview.1673626511

**Comment by RyanTT** [comment]
Hi, I'll put an option into the new release tomorrow, however the customization options will change slightly, I'll update the documentation accordingly

**Comment by RyanTT** [comment]
Added in this version https://www.nuget.org/packages/BytexDigital.Blazor.Components.CookieConsent/1.0.17-preview.1673674203

Please refer to the updated readme, in step 4 you find the optional call to customize the prompt, where also the new setting can be found.

**Comment by RyanTT** [comment]
Feature was added in a preview package
