### ISSUE TITLE
Cookie not saving on production

### ISSUE THREAD

**Issue by SFranciscoSouza** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#20]
Hi!

The Consent is working perfectly on localhost, but when I publish and use it live it doest not save the user selection at all, and keeps poping up everytime.

Am I missing any configuration required to publish? I've followed the step by step exactly as instructed.

**Comment by RyanTT** [comment]
Hi, are you testing on http or https? By default, the cookie is set with the Secure flag set, meaning it will only work with https. You can change this behaviour in the options.

**Comment by SFranciscoSouza** [comment]
Yeah I was testing the live version on http. That was it.

Thank you very much! Awesome work.
