### ISSUE TITLE
UseDefaultConsentPrompt not found?

### ISSUE THREAD

**Issue by cryo75** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#21]
I have a Blazor server-side app with NET7.

I added the following to my `Startup.cs`:

```csharp
services.AddCookieConsent(options =>
{
	options.Revision = 1;
	options.PolicyUrl = "/cookie-policy";

	options.UseDefaultConsentPrompt(prompt =>
	{
		prompt.Position = ConsentModalPosition.BottomRight;
		prompt.Layout = ConsentModalLayout.Bar;
		prompt.SecondaryActionOpensSettings = false;
		prompt.AcceptAllButtonDisplaysFirst = false;
	});
});
```

`UseDefaultConsentPrompt` is not found in any namespace. Where is actually located?

**Comment by RyanTT** [comment]
Hi, it's not released as a stable package yet (doh), but if you switch to the newest preview package on nuget it should be there!

**Comment by cryo75** [comment]
That does the trick!
