### ISSUE TITLE
CookiePolicyOptions and AddCookieConsent

### ISSUE THREAD

**Issue by cryo75** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#22]
Just before adding `services.AddCookieConsent(...)` I am doing:

```csharp
services.Configure<CookiePolicyOptions>(options =>
{
	options.CheckConsentNeeded = context => true;
	options.MinimumSameSitePolicy = SameSiteMode.None;
	options.Secure = CookieSecurePolicy.Always;
});
```

Do I still need `options.CheckConsentNeeded = context => true;` ?

**Comment by RyanTT** [comment]
Hi, the CookiePolicyOptions are a system provided by aspnetcore itself and are not part of this package. In fact, this library and the built in way of aspnetcore do not interact with each other at all (the aspnetcore portion only works on server anyway).

You could leave this out entirely, or to make them work together, make the CheckConsentNeeded lambda call the CookieConsentService of this library and run a check against the set preferences of the user

**Comment by cryo75** [comment]
Do you have an example on how to do this?

**Comment by RyanTT** [comment]
I'll post a snippet later today as I'm not at my pc for a few more hours.

Essentially, in the lambda, you need to get the ServiceProvider of the context and get the service CookieConsentService, use it to fetch the preferences and then do a check if the category you want accepted is already accepted.

Note that aspnetcore only differentiates between "essential" and "non essential" cookies. This lambda is telling aspnetcore of non essential cookies are allowed. This could be e.g. Google Analytics.

**Comment by RyanTT** [comment]
Something like this should work

```csharp
    options.CheckConsentNeeded = context =>
    {
        if (!context.Request.Cookies.TryGetValue(".AspNet.CookieConsent", out var cookieValue)) return true;
        if (string.IsNullOrEmpty(cookieValue)) return true;
        
        try
        {
            var preferences = JsonSerializer.Deserialize<CookiePreferences>(cookieValue);
            
            return !preferences.AllowedCategories.Contains("CategoryYouWantToCheck");
        }
        catch
        {
            return true;
        }
    };
```

**Comment by cryo75** [comment]
Looks good.
