### ISSUE TITLE
Support Blazor-Web-App .NET 8

### ISSUE THREAD

**Issue by ynnob** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#25]
Hey!

I am testing out the .NET 8 preview 6 for Blazor Web App at the moment and i wanted to test your cookie consent nuget.

Sadly it does not seem to work out of the box and no cookie consent will open. Neither automaticly nor via the `CookieConsentService`.
The only differece between Blazor Server and Blazor Web App i could spot is that in the Blazor Server project the cookieconsent.js file gets loaded while the Blazor Web App does not seem to load the js file.

But i cant seem to find any error in the console etc. it just does not show up.

Also just a side note: 
It seems like if a package.json file already exists in a project your nuget will not add code to it.

Maybe you can have a look so we can enjoy your nuget in the upcoming release of .NET 8

Thanks!

**Comment by RyanTT** [comment]
Hello,

do I understand correctly that you tried to use the library in the new Blazor App setting and in the traditional Blazor Server setting?

It should work with Blazor Server that existed prior to .NET 8, however the new Blazor (United) App setup is fundamentally different and I will need some time to figure out how to properly adjust the library to this. 

If using Blazor App, it should still work as long as long as the components of this library are marked with the RenderModeServer attribute, this hasn't been done yet however as it will require the minimum .NET version to be upped to .NET 8, and also this doesn't seem desirable to force this usage.

I'll need to figure out some new approach to enable the usage in Blazor Apps.

**Comment by ynnob** [comment]
Thanks for the fast response. Yes i am talking about the new Blazor Web App template in .Net 8 Preview SDK that conbines webassembly and ssr.

I guess i need to fallback to a classic manual cookie approach in the meantime.

**Comment by RyanTT** [comment]
For the meantime yes.

I'l need a solution that enables usage both in classic WebAssembly projects and in the new Blazor App projects that doesn't force you to use one specific rendering mode and which also enables access to the cookie consent data outside of interactive components.

**Comment by RyanTT** [comment]
@ynnob It seems that I was wrong about how future Blazor United projects work and compatibility should pretty much almost there.

I'll try to get a template of the new Blazor United and see what's missing in the library for good compatibility with the current .NET 8 previews, then document it in the README.

**Comment by ynnob** [comment]
> @ynnob It seems that I was wrong about how future Blazor United projects work and compatibility should be pretty much almost there.
> 
> I'll try to get a template of the new Blazor United and see what's missing in the library for good compatibility with the current .NET 8 previews, then document it in the README.

Happy to hear that! Looking forward for it!

**Comment by RyanTT** [comment]
I've pushed a test package version with support for the new setups.
https://www.nuget.org/packages/BytexDigital.Blazor.Components.CookieConsent/1.1.0-preview.1693095817

Here are the updated installation instructions:
https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent#how-to-install

Please let me know if it works out for you.

**Comment by ynnob** [comment]
Hey! Looks good to me.
I implemented it and it just works. No problems so far. 

Thanks man!

**Comment by ynnob** [comment]
Hey @RyanTT whats the reason for A and B ([Docs](https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent#1-configure-your-apprazor))?

Because if i would use B for example i will get some console errors complaining about a missing dotnet.js file

![image](https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/assets/34171562/186fb337-5f8b-48c6-ac95-dacf61cb044f)

Code:
```
    <BytexDigital.Blazor.Components.CookieConsent.CookieConsentHandler @rendermode="@RenderMode.Server" />
    <BytexDigital.Blazor.Components.CookieConsent.CookieConsentInitializer @rendermode="@RenderMode.WebAssembly" />
```

Changing the CookieConsentInitializer  to RenderMode.Server does not display this error. But with and without the error it seems to work correctly.

**Comment by RyanTT** [comment]
The cookie consent initializer has the job of making sure everything in WASM is hooked up correctly if you render the UI on the server instead. If you do not use WASM though, you can skip this (and as you can see it will error out if WASM isn't used by the rest of the app).

This is only necessary if you render the UI on one side and also have components interacting with the CookieConsent lib on the other side (e.g. rendered on Server but also used in WASM)

I forgot to update the docs for this use case

**Comment by RyanTT** [comment]
I've updated installation steps for Blazor Web Apps to explain when adding what is necessary. Please let me know if it's understandable.
