### ISSUE TITLE
Feature Request: Reject all Button

### ISSUE THREAD

**Issue by ynnob** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#26]
The tendency of cookie banners in the EU and by the GDPR is more and more in the direction that the user must be given the possibility to reject all non-essential cookies.

Please add an option for a "reject all" button that rejects all cookies. Maybe just in the style of the "change preference" button or even without background. Then you could reduce the height of the other two buttons a bit and it should fit from the design point of view.

So far everything runs fine in .NET 8 RC2

**Comment by Arkensor** [comment]
Hello @ynnob,

thank you for your feedback. What would the reject-all button do compared to the existing "Decline" button?

**Comment by ynnob** [comment]
> Hello @ynnob,
> 
> 
> 
> thank you for your feedback. What would the reject-all button do compared to the existing "Decline" button?

Am i missing a option in the dev branch?
Currently there is no decline button in my setup.

![image](https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/assets/34171562/200358b5-98b2-4c54-bbf7-89b99ce4b7c2)

**Comment by RyanTT** [comment]
If `SecondaryActionOpensSettings` is set to false and atleast one category exists that isn't set to `IsRequired = true`, then the button "Decline" will show up, which only accepts the categories marked as required. Also, then above/left of the buttons, the option to open the preferences should show up.

**Comment by ynnob** [comment]
Oh wow youre right. I did not see the "Preference setting" in the bottom left.

It was hidden in plain sight 😓 
Thank oyu guys!
