### ISSUE TITLE
Issues with Blazor Web App setup

### ISSUE THREAD

**Issue by AlbertoPa** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#28]
When configuring the .Net 8 blazor web app, following the instructions, I face two issues:

```
<BytexDigital.Blazor.Components.CookieConsent.CookieConsentInitializer @rendermode="@RenderMode.Server" />
```
is not found. and, when adding 

```
builder.Services.AddCookieConsent(o =>
{
    // The same configuration as on the server! Best to put this lambda in a shared project to reuse to reduce duplication.
}, withUserInterface: false);
```

no ``AddCookieConsent`` which takes two inputs is found.

**Comment by RyanTT** [comment]
Hey, are you using the latest preview version of the library?

**Comment by AlbertoPa** [comment]
I was using 1.0.18 (stable).

**Comment by RyanTT** [comment]
Please try the latest preview, it should work there. I haven't pushed this build to a stable release yet but will do that soon.

**Comment by AlbertoPa** [comment]
Testing right now :-)

P.S. Do you have guidelines for auto rendermode? Should we use the InteractiveServer/InteractiveWebAssembly settings as in the example, or just use InteractiveAuto?

**Comment by AlbertoPa** [comment]
The preview version works. The only issue I found is that it seems to have one problem when trimming:

![image](https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/assets/423032/e644c750-c71c-4c8e-b09a-51b2387cf800)

Other than that, it works fine. Thank you for your help.
