### ISSUE TITLE
Manually open the preferences modal

### ISSUE THREAD

**Issue by rubsy92** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#3]
Hi,

Thank you for this library, it's amazing! I just have a question regarding the manually opening of the preferences modal. It requires a "CookieConsentService" object, which can be declared with a new statement. This new statement requires IJSRuntime which can be injected, but I don't seem to be able to figure out how I should declare the options tag. Could you add an examle of this to the readme please?

Thanks!

**Comment by RyanTT** [comment]
Hello,

glad you're finding the library useful! The CookieConsentService is part of the dependency container, so you can simply inject it where required e.g. with the `[Inject]` attribute.

**Comment by rubsy92** [comment]
Hi,

Thank you for the fast reply! I got it working!

And what about the "Show cookie policy" link? Now it links to nowhere. Can I assign a link to it? Or delete that link?

Thanks again

**Comment by RyanTT** [comment]
Hi,

glad it's working!

You can change the cookie policy link with the options:

https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/blob/master/BytexDigital.Blazor.Components.CookieConsent/CookieConsentOptions.cs#L27

The options are configured inside the `AddCookieConsent` lambda inside your Program.cs.

**Comment by rubsy92** [comment]
Hi,

Thanks for the fast reposonse! It's working great!

**Comment by RyanTT** [comment]
No problem. May I ask how you found this library?

**Comment by rubsy92** [comment]
Hi, 

I found it through a Reddit-post after a Google search for cookie consent in Blazor.
