### ISSUE TITLE
Hangs during build process

### ISSUE THREAD

**Issue by devtrix** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#33]
It used to work in the past and I am very used to this library but recently when I created a new Blazor 8 WebApp, added the nuget package, configured the service and add the Tag in Routes.razor; it wont build.  I am not getting any error messages at all.  Just won't finish building.  If I remove the Tag(s), it builds just fine.  I have tried this with v1.0.18 & v1.2.0-preview.1698872627, with the same result.
Any help is much appreciated.  
Thanks

**Comment by RyanTT** [comment]
Hey,

did you try cleaning your solution? You could also try to enable detailed build logs to narrow down why it's failing.

**Comment by devtrix** [comment]
Yes I did.  I have attached the Build Output.  Looks like the Bytex npm has errors.

**Comment by devtrix** [comment]
[Output-Build.zip](https://github.com/user-attachments/files/16116755/Output-Build.zip)

**Comment by RyanTT** [comment]
I can't say I've seen this behavior before, but to me it looks like your build tool is trying to build files from the library that aren't meant to be touched by it.

Could you post your projects csproj?

**Comment by devtrix** [comment]
[BlazorTestApp.zip](https://github.com/user-attachments/files/16117734/BlazorTestApp.zip) 
I have sent a new Blazor App. Please change the extension to .7z.  So the whole file is BlazorTestApp.7z.  
The zip was 56 MB and GitHub wont allow 7z extension.

**Comment by devtrix** [comment]
So wth happened?  No comments, no help?

**Comment by devtrix** [comment]
I am not sure why I am facing this on 3 different machines with 3 other projects. Since it has been over 3 weeks  and no response, I  ended up writing my own.  Good luck fellas.

**Comment by RyanTT** [comment]
Hey, terribly sorry about the lack of a response here.

I did check your provided zip project and updated it's cookie consent dependency to the newest version, and it built and ran perfectly fine on my machine. Both in VS2022 and in Rider.

Looking at your log, it seems to be erroring out because your compiler is trying to find all .ts-files to compile. I wouldn't know why it's doing that though, maybe you have some plugin installed? I am sadly not too familiar with the build process in VS myself so I'm not sure where my installation and yours differ here, I only know that my fresh installation of VS22 is not producing this error. Especially this leads me to believe it must be some configuration within your VS or a plugin.

**Comment by devtrix** [comment]
Finally figured out what the issue was.  When you install the Nuget package, it shows that the npm dependencies are not installed.  It seems that if I installed it, it has this behavior.  If I just let it be, then the build process continues. But now I have a different issue; happening both in v1.1.18 or 1.2.0.  I get a javascript error:
Error: One or more errors occurred. (Root component type 'BytexDigital.Blazor.Components.CookieConsent.CookieConsentHandler' could not be found in the assembly 'BytexDigital.Blazor.Components.CC'.)

**Comment by devtrix** [comment]
Opening a new issue with the JS error.

**Comment by richardu** [comment]
Hi,
I'm having this issue as well.
What's the reason for using npm?
Is it possible to disable it?
Thanks,
Richard

**Comment by RyanTT** [comment]
NPM is used to build the tailwind css classes. But it's definitely not needed in the final package, so I'll add a step to the build process to remove the package json and NPM dependencies on publish to nuget. That should also get rid of this issue for you guys 👍

**Comment by richardu** [comment]
Great stuff, thanks very much @RyanTT! 🙂

**Comment by RyanTT** [comment]
Please check if this issue still persists in the latest preview

https://www.nuget.org/packages/BytexDigital.Blazor.Components.CookieConsent/1.2.1-preview.1723683378
