### ISSUE TITLE
BytexDigital.Blazor.Components.CookieConsent.CookieConsentHandler' could not be found

### ISSUE THREAD

**Issue by devtrix** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#35]
I have an issue happening both in v1.1.18 or 1.2.0. I get a javascript error  in the Dev Console:
Error: One or more errors occurred. (Root component type 'BytexDigital.Blazor.Components.CookieConsent.CookieConsentHandler' could not be found in the assembly 'BytexDigital.Blazor.Components.CC'.)

**Comment by RyanTT** [comment]
Will look into this today/tomorrow!

**Comment by RyanTT** [comment]
As an initial question: Do you have a Blazor WASM client project and a server project that both build together? And what  .NET version are you using?

**Comment by devtrix** [comment]
> As an initial question: Do you have a Blazor WASM client project and a server project that both build together? And what .NET version are you using?

 I am using it in a Blazor 8 WebApp with Auto mode & Per Page Interactivity.

**Comment by RyanTT** [comment]
Could you verify the setup is the same as in this example project? Including which project has the nuget package installed

[BlazorApp1.zip](https://github.com/user-attachments/files/16503799/BlazorApp1.zip)

**Comment by devtrix** [comment]
> Could you verify the setup is the same as in this example project? Including which project has the nuget package installed
> 
> [BlazorApp1.zip](https://github.com/user-attachments/files/16503799/BlazorApp1.zip)

Thats it.  I see that you have the Interactivity: Global chosen & the Bytex is insta;lled on the web assembly side.  I used Interactivity: PerPage & the nuget is on the server side. Thats the issue.  If the docs can reflect this it would be great.  I am closing this issue, thanks a lot. Ciao.
